### ISSUE TITLE
[Bug]. Import/Export Function is broken: `Cannot read properties of undefined (reading 'getActivity')`

### ISSUE THREAD

**Issue by NA0341** [Akylas/com.akylas.documentscanner#19] opened 2023-12-17 13:16 UTC
**Steps to reproduce:**

1. Export config.
2. Import config
3. Click on "Restart" -> The following Message appears: `Cannot read properties of undefined (reading 'getActivity')`

It needs to be checked whether this is a bug in import or export.

Here's the config file: 
[alpimaps_settings_2023-12-17.json](https://github.com/Akylas/com.akylas.documentscanner/files/13696213/alpimaps_settings_2023-12-17.json)

OSS Document Scanner Version: 1.1.4 Build 9

System & Device Info:
OS version: 9
Bootloader: G950FXXUCDVI1, VM: ART
Kernel: 4.4.111-21427293
Brand: samsung, Model: SM-G950F
Board: universal8895, Manufacturer: samsung

SDK
Target: 28, Min: 17

Security
Root: false
Encryption: Encrypted (FDE)
Patch level: April 1, 2021

**Comment by Raj9039852537** [comment] 2023-12-18 09:28
On export settings received this error 
![Screenshot_20231218-145631](https://github.com/Akylas/com.akylas.documentscanner/assets/11007352/1d877c18-449f-42b3-a895-fb34ce0900b9)

**Comment by farfromrefug** [comment] 2023-12-18 10:28
@Raj9039852537 thanks i fixed all those bugs. New release today

**Comment by Raj9039852537** [comment] 2023-12-19 15:54
> @Raj9039852537 thanks i fixed all those bugs. New release today

Not solved in latest version 10
showing same error as above

**Comment by farfromrefug** [comment] 2023-12-19 16:07
@Raj9039852537 OK thought it would be fixed. will look again. thanks

**Comment by Raj9039852537** [comment] 2023-12-19 16:14
> @Raj9039852537 OK thought it would be fixed. will look again. thanks

Also manual cropping does not work

**Comment by farfromrefug** [comment] 2023-12-19 16:46
@Raj9039852537 what do you mean ? changing the crop after with the recrop button ?

**Comment by Raj9039852537** [comment] 2023-12-19 16:52
Yes 
For example  if auto crop done on image which is not precise, I re crop it with recrop button, which selected correct area but clicking on ✔️ button doesn't apply desired changes to the document .

**Comment by farfromrefug** [comment] 2023-12-19 16:53
@Raj9039852537 thanks must have broken something as it was working. will look

**Comment by farfromrefug** [comment] 2023-12-19 19:57
> > @Raj9039852537 thanks i fixed all those bugs. New release today
> 
> Not solved in latest version 10 showing same error as above File gets created by no content gets written

Actually you say the same error but you now the file exists but is empty. Do you still see the error dialog with `FileNotFoundException` ? I can t reproduce it here but it feels like it creates a folder instead of a file

**Comment by Raj9039852537** [comment] 2023-12-20 03:26
I said same error because as you can see in screenshot just taken it provides same exception with just different file name which is actually changed in one commit by you.
![Screenshot_20231220-085440](https://github.com/Akylas/com.akylas.documentscanner/assets/11007352/d701715e-4d32-44c1-a6e7-2dbc2dbd3c0f)

**Comment by Raj9039852537** [comment] 2023-12-20 03:47
Thanks Re crop bug is fixed in release  11

**Comment by farfromrefug** [comment] 2023-12-20 07:28
> I said same error because as you can see in screenshot just taken it provides same exception with just different file name which is actually changed in one commit by you. 
> 
> also in error file looked for is inside of a folder which is of same name which doesn't exist

Ok sorry for now i dont see what the issue is as i cant reproduce. Will try on multiple devices

**Comment by user8446** [comment] 2024-01-02 00:09
I tried on my Android 14 device and also receive the error:

![Screenshot_20240101-190636](https://github.com/Akylas/com.akylas.documentscanner/assets/18019245/85dfe188-a3e4-4604-a80b-9ff6d5b68d8c)


A 0 byte file gets saved:


![Screenshot_20240101-190704](https://github.com/Akylas/com.akylas.documentscanner/assets/18019245/8bd3266a-17d2-4c12-9f6d-2c02e26e3177)

**Comment by farfromrefug** [comment] 2024-01-02 21:37
@user8446 @Raj9039852537 i think i finally fixed it. Look at the latest version

**Comment by user8446** [comment] 2024-01-03 19:52
Yes I checked and on my device the backup saves correctly with version 1.2.15.25... nice work!

**Comment by Raj9039852537** [comment] 2024-01-04 02:24
> @user8446 @Raj9039852537 i think i finally fixed it. Look at the latest version

Export function works fine now. 👍

import function got this error.
![Screenshot_20240104-075315](https://github.com/Akylas/com.akylas.documentscanner/assets/11007352/2c6172f1-219d-4e1d-b8ab-ed741c662cdf)

**Comment by user8446** [comment] 2024-01-04 02:56
I have the same error in import as well. 

Sorry I should have checked that.

**Comment by farfromrefug** [comment] 2024-01-04 07:45
@Raj9039852537 @user8446 it is me who is sorry :) will fix it

**Comment by farfromrefug** [comment] 2024-01-04 21:09
@Raj9039852537 @user8446 should be fixed in latest.

**Comment by Raj9039852537** [comment] 2024-01-05 11:13
Finally solved 👍

**Closed** 2024-01-05 13:20 UTC
Labels: bug

**Comment by user8446** [comment] 2024-01-06 16:19
Yes export and import both work as expected!

**Comment by NA0341** [comment] 2024-01-14 08:49
Version 1.2.25 Build 35 produces empty output again.

With the following message: `Write TextTask returns no result.`

**Comment by farfromrefug** [comment] 2024-01-14 14:32
@NA0341 sorry about that. will fix it
